default:
  POSTGRES:
    echo: false
    echo_pool: false
    driver: postgresql+asyncpg
    port: 7432
    user: sampleuser
    host: 89.169.160.205
    password: sampleuser2024
    database: sampledb
    pool_pre_ping: true
    pool_recycle: 3000

  S3:
    chat_file_folder: chat_file_folder
    bucket_name: regulatrix
    port: 443
    host: ""
    protocol: https
    verify: true
    access_key: ""
    secret_key: ""
    version: s3v4
    expiration_time_link_object: 3600
    expiration_time_link_archive_order: 86400 # 3600 * 24