"""auto

Revision ID: f1cb2f0c86f8
Revises: 
Create Date: 2024-09-06 16:40:11.192415+03:00

"""

import sqlalchemy as sa
from alembic import op
# revision identifiers, used by Alembic.
revision = "f1cb2f0c86f8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("login", sa.String(), nullable=True, comment="Логин пользователя"),
        sa.Column("user_name", sa.String(), nullable=True, comment="Имя пользователя"),
        sa.Column("password", sa.String(), nullable=True, comment="Пароль"),
        sa.Column(
            "file_url",
            sa.String(),
            nullable=True,
            comment="Ссылка на изображение пользователя",
        ),
        sa.Column(
            "file_name", sa.String(), nullable=True, comment="Наименование изображения"
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Идентификатор",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Пользователь",
    )
    op.create_table(
        "chat",
        sa.Column("context", sa.Text(), nullable=True, comment="Контекст чата"),
        sa.Column("title", sa.Text(), nullable=False, comment="Заголовок чата"),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Идентификатор",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Чат",
    )
    op.create_table(
        "chat_file",
        sa.Column("chat_id", sa.Integer(), nullable=True, comment="Идентификатор чата"),
        sa.Column("file_url", sa.String(), nullable=False, comment="Ссылка на файл"),
        sa.Column(
            "file_name", sa.String(), nullable=False, comment="Наименование файла"
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Идентификатор",
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Файл чата",
    )
    op.create_table(
        "message",
        sa.Column("chat_id", sa.Integer(), nullable=True, comment="Идентификатор чата"),
        sa.Column("message", sa.Text(), nullable=True, comment="Сообщение"),
        sa.Column(
            "message_type",
            sa.Enum("AI", "USER", name="messagetypeenum"),
            nullable=False,
            comment="Тип сообщения",
        ),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Идентификатор",
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Сообщение\n    @message_type",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    op.drop_table("chat_file")
    op.drop_table("chat")
    op.drop_table("user")
    # ### end Alembic commands ###
