default:
  NAME: AI_HACK_SERVICE
  PORT: 8060
  HOST: 0.0.0.0
  CORS_ORIGINS: [ "*" ]
  DEBUG: false
  RELOADED: false

  S3:
    data_file_folder: data
    bucket_name: regulatrix
    port: 443
    protocol: https
    verify: true
    version: s3v4
    expiration_time_link_object: 3600
    expiration_time_link_archive_order: 86400 # 3600 * 24

    host: ""
    access_key: ""
    secret_key: ""



  LOGGING:
    version: 1
    disable_existing_loggers: false
    formatters:
      default:
        format: '[%(asctime)s] %(levelname)-8s# %(filename)s[LINE:%(lineno)d] %(message)s'
    handlers:
      console:
        level: INFO
        class: logging.StreamHandler
        formatter: default
        stream: ext://sys.stdout
      error:
        level: ERROR
        class: logging.StreamHandler
        formatter: default
        stream: ext://sys.stderr
    loggers:
      default:
        level: DEBUG
        handlers: [ console, error ]
    root:
      level: DEBUG
      handlers: [ console, error ]